name: podcast
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0 # Or latest version
  xml: ^6.3.0   # Or latest version
  just_audio: ^0.9.36
  collection: ^1.18.0
  just_audio_windows: ^0.2.2
  # cupertino_icons: ^1.0.8 # Or latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
